# To recreate:
#   conda env export --file environment.yml --from-history
# Uv and pip should use requirements.txt.
# Select python<3.12 to match vim --version.
name: vim-python
channels:
  - conda-forge
dependencies:
  - python # [version='<3.13']
  - vim
